### ISSUE TITLE
Error during inference

### ISSUE THREAD

**Issue by sauradip** [maria-korosteleva/Garment-Pattern-Estimation#1]
Hi,

Thanks for making the code of this awesome work public. 

I faced this error when running 
`python nn/evaluation_scripts/on_test_set.py -st models/baseline/lstm_stitch_tags.yaml
`

![Screenshot from 2022-08-11 22-48-37](https://user-images.githubusercontent.com/23197350/184248500-528210b7-b8f6-434d-9c35-5477e0e1023c.png)

Can you suggest me how to solve this. Thanks in advance

**Comment by maria-korosteleva** [comment]
Hi @sauradip 
Thank you for your interest in our work! Sorry for the late reply
The errors you see look like errors in the dataset -- the script can not find expected paths. Have downloaded the dataset and set up the paths in `system.json` correctly?
The path to the data in `system.json` should point to a root folder with per-garment-type subfolders

**Comment by sauradip** [comment]
Thanks for the response. Also want to know if the garment pattern mask can be generated from the annotation sequence ?

**Comment by maria-korosteleva** [comment]
I'm not quite sure what you mean by pattern mask and annotation sequence in this context. The dataset has a number of annotations, including segmentation masks that indicate parts of geometry corresponding to the individual panels (2D pieces of "fabric") of sewing patterns
The models only output the sewing patterns, but not the segmentation mask

**Comment by sauradip** [comment]
Thanks for the response, it really helped me solve the doubts. A follow-up question to this , you have shown the unseen garment types inference in Table 1. I am curious to know if my understanding is correct -- I only have (1) Pointcloud of useen garment type (2) I know that the unseen garment type produces a few among the 23 patterns let say. If so then do i know any additional hint about the unseen garment type , atleast the name of the garment-type do i know ? What i understood by unseen -type is this point-cloud of such garment types are not used during training. Is that so ? It is a bit complicated to understand this from the code so asking it for better clarity.

**Comment by maria-korosteleva** [comment]
A point cloud is the only input that the network is given, for both seen and unseen garment types. Unseen garment types just fall into a design distribution outside of the training data. For the evaluation on unseen types, we use the garments from the "test" folder of our dataset (https://zenodo.org/record/5267549#.Yxr-g3Yza5d). You can find more details and examples of how the unseen garments were constructed in our [dataset paper](https://arxiv.org/abs/2109.05633)

**Comment by sauradip** [comment]
Thanks for the response. It helped a lot. I also had another query regarding the panel classes.

Why is "top_front_right" merged in "top_right" class in https://github.com/maria-korosteleva/Garment-Pattern-Estimation/blob/master/nn/data_configs/panel_classes_condenced.json whereas https://github.com/maria-korosteleva/Garment-Pattern-Estimation/blob/master/nn/data_configs/panel_classes_plus_one.json has 24 classes. I saw in the implementation condensed.json is used. Any reason ?

**Comment by maria-korosteleva** [comment]
You are welcome!

Yes, there is: we experimented with different options for class grouping.
Please, refer to our paper, Section 7.5.1 for more details. The
condensed version was showing better performance.

пн, 17 окт. 2022 г. в 10:16, Sauradip Nag ***@***.***>:
