### ISSUE TITLE
How to use multi Gpus?

### ISSUE THREAD

**Issue by jingfengguo-ai** [maria-korosteleva/Garment-Pattern-Estimation#12]
Hello, in your paper and code mentioned multi-GPU training, but in the actual training process only a single GPU is specified, https://github.com/maria-korosteleva/Garment-Pattern-Estimation/blob/a28f047e41cd96e5d844a32a94c0f3c9a8d0dfa3/nn/trainer.py#L62 and my training speed is very slow, GPU utilization is very low, I would like to ask you have any good training advice?

**Comment by maria-korosteleva** [comment]
To use multiple GPUs list their names in this parameter: https://github.com/maria-korosteleva/Garment-Pattern-Estimation/blob/master/models%2Fatt%2Fatt.yaml#L145

If your single GPU is not fully utilized, the general advice is to increase the batch size untill training fills up all your resources. Note this is an old project that was trained on GPUs with smaller memory than is available in modern GPUs, so low utilization is to be expected
