### ISSUE TITLE
does it work with general 3d objects?

### ISSUE THREAD

**Issue by destlaver** [maria-korosteleva/Garment-Pattern-Estimation#4]
Hi, great work here. I was wondering if it could be used to predict sewing patterns for a dog plush for example

**Comment by maria-korosteleva** [comment]
Hi @destlaver, thank you! 😊

If I understand correctly, plush patterns can follow the same sewing pattern structure as garments, so I don't see why not! As long as you have a suitable dataset to train the model on 

There might be some caveats, e.g. representing higher degrees of curvatures... Grouping of panel classes (needed for unseen generalization) might not be as straightforward, but I believe it's all solvable

**Comment by destlaver** [comment]
Sadly I haven't any training set. How many samples do you think are needed?

**Comment by maria-korosteleva** [comment]
We used 12000-20000 samples in our training dataset. I think this number
could be a good guideline for your problem. However, it will depend on the
amount of variation in your data that you would like to cover =)

пт, 10 мар. 2023 г. в 11:23, destlaver ***@***.***>:
