### ISSUE TITLE
error while importing customconfig

### ISSUE THREAD

**Issue by DavMLPath** [maria-korosteleva/Garment-Pattern-Estimation#5]
![image](https://user-images.githubusercontent.com/114501323/224725110-f360aa2d-6321-4190-9191-96d7388c0783.png)

Hello! 
I am having trouble to import this library, while running evaluation commands.

can you please give me a hint what can be an issue?
 File "/home/davo/Desktop/Garment_Estimation/Garment-Pattern-Estimation/./nn/evaluation_scripts/on_test_set.py", line 17, in <module>
    import customconfig

**Comment by maria-korosteleva** [comment]
Hi, thank you for your interest in our work!

Please, check that you added custom dependencies to your environmental
variables (PYTHONPATH). That should do the trick!
Here are the instructions:
https://github.com/maria-korosteleva/Garment-Pattern-Estimation/blob/master/docs/Installation.md#5-custom-dependencies-access

пн, 13 мар. 2023 г. в 15:07, DavMLPath ***@***.***>:
